# Generated by Django 5.0.3 on 2024-05-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
