# Generated by Django 5.0.3 on 2024-05-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_worker_full_name_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('matriculation_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=11)),
                ('birthday', models.DateField()),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('genotype', models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('SC', 'SC')], max_length=2)),
                ('address', models.TextField()),
                ('patient_height', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='patients/')),
                ('mothers_number', models.CharField(max_length=11)),
                ('fathers_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
