# Generated by Django 5.0.3 on 2024-05-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patientprofile_delete_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='fathers_number',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='mothers_number',
        ),
    ]
