# Generated by Django 5.0.3 on 2024-05-30 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_patientprofile_fathers_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='fathers_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='mothers_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
