# Generated by Django 5.0.3 on 2024-05-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_patientprofile_fathers_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='matriculation_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
