# Generated by Django 5.0.3 on 2024-05-31 17:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_date_vitalsigns_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsigns',
            name='created_at',
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='blood_pressure',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='pulse',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='weight',
            field=models.FloatField(),
        ),
    ]
