# Generated by Django 5.0.3 on 2024-05-31 18:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_vitalsigns_created_at_vitalsigns_entry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsigns',
            name='entry_date',
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='blood_pressure',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='pulse',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='temperature',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='weight',
            field=models.CharField(max_length=10),
        ),
    ]
