# Generated by Django 5.0.3 on 2024-06-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_vitalsigns_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('nurse', 'Nurse'), ('doctor', 'Doctor')], max_length=20),
        ),
    ]
