# Generated by Django 5.0.3 on 2024-06-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='treatment_given',
            field=models.BooleanField(default=False),
        ),
    ]
