# Generated by Django 5.0.3 on 2024-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_prescription_doctor_alter_prescription_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='status',
            field=models.CharField(default='Posted to Dr', max_length=20),
        ),
    ]
