# Generated by Django 5.0.3 on 2024-06-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_vitalsigns_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='status',
            field=models.CharField(default='Not Started', max_length=20),
        ),
    ]
