# Generated by Django 5.0.3 on 2024-06-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_vitalsigns_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='treatment_given',
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Started', 'Started'), ('Sent for Treatment', 'Sent for Treatment')], default='Not Started', max_length=20),
        ),
    ]
