# Generated by Django 5.0.3 on 2024-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_prescription_treatment_given_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='treatment_status',
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment_given',
            field=models.BooleanField(default=False),
        ),
    ]
