# Generated by Django 5.0.3 on 2024-06-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_prescription_treatment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='treatment_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
