# Generated by Django 5.0.3 on 2024-06-03 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_message_read_alter_message_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='test',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='diagnosis',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='drugs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='symptoms',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='tests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='treatment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
